<a href="https://colab.research.google.com/github/GeorgieWasTaken/marmeladki/blob/main/Task2_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#📌 Урок: Работа с файлами
##📖 Теоретический минимум

Текстовые файлы (.txt) - простые файлы с неструктурированным текстом

CSV (Comma-Separated Values) - табличные данные с разделителями

Excel (.xlsx, .xls) - электронные таблицы с расширенными возможностями

JSON - структурированные данные в формате ключ-значение

Бинарные файлы - изображения, PDF и другие нетекстовые форматы

# 🔹 Основные операции с файлами
Открытие/закрытие файла

Чтение данных

Запись данных

Обработка больших файлов


#📖 Материалы

https://vkvideo.ru/video-194554202_456239677

https://vkvideo.ru/video-194554202_456239682









# 🏆 Задания

## 1️⃣ Работа с текстовыми файлами
**Задача:**
 Создать текстовый файл, записать в него str данные и прочитать обратно

In [1]:
text = "Пример текста"

with open("example.txt", "w", encoding="utf-8") as file:
    file.write(text)

with open("example.txt", "r", encoding="utf-8") as file:
    content = file.read()

print(content)

Пример текста



## 2️⃣ Работа с CSV файлами

**Задача:**

Создать CSV файл с табличными данными, записать и прочитать его



In [2]:
import csv

data = [
    ["name", "age"],
    ["Alice", 25],
    ["Bob", 30]
]

with open("data.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerows(data)

with open("data.csv", "r", encoding="utf-8") as file:
    reader = csv.reader(file)

    for row in reader:
        print(row)

['name', 'age']
['Alice', '25']
['Bob', '30']


## 3️⃣  Работа с Excel файлами
**Задача:** Создать Excel файл и прочитать данные из него

Используйте библиотеку pandas

---



In [3]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Alice", "Bob"],
    "age": [25, 30]
})

df.to_excel("data.xlsx", index=False)

result = pd.read_excel("data.xlsx")

print(result)

    name  age
0  Alice   25
1    Bob   30



## 4️⃣  Чтение больших файлов по частям


**Задача:** Обработать файл построчно без загрузки в память целиком

Реализуйте чанки самостоятельно или воспользуйтесь chunk из pandas

---




In [4]:
with open("big_file.txt", "w", encoding="utf-8") as file:
    for i in range(1000):
        file.write(f"Строка {i}\n")

chunk_size = 100

with open("big_file.txt", "r", encoding="utf-8") as file:

    chunk = []

    for line in file:
        chunk.append(line.strip())

        if len(chunk) == chunk_size:
            print(chunk)
            chunk = []

    if chunk:
        print(chunk)

['Строка 0', 'Строка 1', 'Строка 2', 'Строка 3', 'Строка 4', 'Строка 5', 'Строка 6', 'Строка 7', 'Строка 8', 'Строка 9', 'Строка 10', 'Строка 11', 'Строка 12', 'Строка 13', 'Строка 14', 'Строка 15', 'Строка 16', 'Строка 17', 'Строка 18', 'Строка 19', 'Строка 20', 'Строка 21', 'Строка 22', 'Строка 23', 'Строка 24', 'Строка 25', 'Строка 26', 'Строка 27', 'Строка 28', 'Строка 29', 'Строка 30', 'Строка 31', 'Строка 32', 'Строка 33', 'Строка 34', 'Строка 35', 'Строка 36', 'Строка 37', 'Строка 38', 'Строка 39', 'Строка 40', 'Строка 41', 'Строка 42', 'Строка 43', 'Строка 44', 'Строка 45', 'Строка 46', 'Строка 47', 'Строка 48', 'Строка 49', 'Строка 50', 'Строка 51', 'Строка 52', 'Строка 53', 'Строка 54', 'Строка 55', 'Строка 56', 'Строка 57', 'Строка 58', 'Строка 59', 'Строка 60', 'Строка 61', 'Строка 62', 'Строка 63', 'Строка 64', 'Строка 65', 'Строка 66', 'Строка 67', 'Строка 68', 'Строка 69', 'Строка 70', 'Строка 71', 'Строка 72', 'Строка 73', 'Строка 74', 'Строка 75', 'Строка 76', 'Строка 


## 5️⃣ Чтение JPEG файла
**Задача:**

Создайте изображение 21х21 пиксель в формате JPEG

Прочитайте JPEG файл в бинарном режиме и преобразуйте картинку в черно белую

Выведете прочитанный файл как массив интенсивности пикселей

---


In [1]:
from PIL import Image
import numpy as np

image = Image.new("RGB", (21, 21), color="blue")

image.save("image.jpg", "JPEG")

with open("image.jpg", "rb") as file:
    binary_data = file.read()

print(binary_data[:50])

img = Image.open("image.jpg")

gray_img = img.convert("L")

pixel_array = np.array(gray_img)

print(pixel_array)

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\t\t\x08\n\x0c\x14\r\x0c\x0b\x0b\x0c\x19\x12\x13\x0f'
[[29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29 2